SportsEventApp/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsEvent.Domain.Domain;
using SportsEvent.Service.Interface;

namespace SportsEventApp.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IMatchService _matchService;
        private readonly ITeamService _teamService;
        private readonly ISportEventService _sportEventService;
        private readonly ITicketService _ticketService;

        public MatchesController(IMatchService matchService, ITeamService teamService, ISportEventService sportEventService, ITicketService ticketService)
        {
            _matchService = matchService;
            _teamService = teamService;
            _sportEventService = sportEventService;
            _ticketService = ticketService;
        }



        // GET: Matches
        public IActionResult Index()
        {
            ViewData["TeamNames"] = _teamService.GetAllTeams().ToDictionary(t => t.Id, t => t.Name);
            ViewData["SportEventNames"] = _sportEventService.GetAllSportEvents().ToDictionary(se => se.Id, se => se.Name);

            return View(_matchService.GetAllMatches());
        }

        // GET: Matches/Details/5
        public IActionResult Details(Guid? id)
        {
            ViewData["TeamNames"] = _teamService.GetAllTeams().ToDictionary(t => t.Id, t => t.Name);
            ViewData["SportEventNames"] = _sportEventService.GetAllSportEvents().ToDictionary(se => se.Id, se => se.Name);

            if (id == null)
            {
                return NotFound();
            }

            Match match = _matchService.GetMatch(id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // GET: Matches/Create
        public IActionResult Create()
        {
            List<Team> teams = _teamService.GetAllTeams();
            ViewData["Team1Id"] = new SelectList(teams, "Id", "Name");
            ViewData["Team2Id"] = new SelectList(teams, "Id", "Name");
            ViewData["SportEventId"] = new SelectList(_sportEventService.GetAllSportEvents(), "Id", "Name");

            return View();
        }

        // POST: Matches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Date,Location,Score,TeamId1,TeamId2,SportEventId,Id")] Match match)
        {
            if (ModelState.IsValid)
            {
                match.Id = Guid.NewGuid();
                _matchService.AddMatch(match);

                return RedirectToAction(nameof(Index));
            }

            ViewData["Team1Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId1);
            ViewData["Team2Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId2);
            ViewData["SportEventId"] = new SelectList(_sportEventService.GetAllSportEvents(), "Id", "Name", match.SportEventId);

            return View(match);
        }

        // GET: Matches/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = _matchService.GetMatch(id);
            if (match == null)
            {
                return NotFound();
            }

            ViewData["Team1Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId1);
            ViewData["Team2Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId2);
            ViewData["SportEventId"] = new SelectList(_sportEventService.GetAllSportEvents(), "Id", "Name", match.SportEventId);

            return View(match);
        }

        // POST: Matches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Date,Location,Score,TeamId1,TeamId2,SportEventId,Id")] Match match)
        {
            if (id != match.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _matchService.UpdateMatch(match);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchExists(match.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team1Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId1);
            ViewData["Team2Id"] = new SelectList(_teamService.GetAllTeams(), "Id", "Name", match.TeamId2);
            ViewData["SportEventId"] = new SelectList(_sportEventService.GetAllSportEvents(), "Id", "Name", match.SportEventId);

            return View(match);
        }

        // GET: Matches/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Match match = _matchService.GetMatch(id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // POST: Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            Match match = _matchService.GetMatch(id);
            if (match != null)
            {
                _matchService.DeleteMatch(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool MatchExists(Guid id)
        {
            return _matchService.GetMatch(id) != null;
        }


        public IActionResult BuyTicket(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = _matchService.GetMatch(id);

            Ticket t = new Ticket();

            if (t != null)
            {
                t.MatchId= match.Id;
                t.Match = match;
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                 
            }

            return View(t);
        }

        [HttpPost]
        public IActionResult TicketBought(Ticket model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _ticketService.CreateTicket(model);



            return View("Index", _ticketService.GetAllTickets());
        }

    }
}

SportsEventApp/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportsEvent.Domain.Domain;
using SportsEvent.Service.Implementation;
using SportsEvent.Service.Interface;
using SportsEventApp.Repository;

namespace SportsEventApp.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITicketService ticketService;
        private readonly IMatchService matchService;

        private readonly IShoppingCartService shoppingCartService;

        public TicketsController(ITicketService ticketService, IMatchService matchService, IShoppingCartService shoppingCartService)
        {
            this.ticketService = ticketService;
            this.matchService = matchService;
            this.shoppingCartService = shoppingCartService;
        }


        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var tickets = ticketService.GetAllTickets();
            return View(tickets);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = ticketService.GetTicket(id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["MatchId"] = new SelectList(matchService.GetAllMatches(), "Id", "Location");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MatchId,Price,Tribina,Red,Sedishte,Id")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.Id = Guid.NewGuid();
                ticketService.CreateTicket(ticket);
                
                return RedirectToAction(nameof(Index));
            }
            ViewData["MatchId"] = new SelectList(matchService.GetAllMatches(), "Id", "Location", ticket.MatchId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = ticketService.GetTicket(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["MatchId"] = new SelectList(matchService.GetAllMatches(), "Id", "Location", ticket.MatchId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("MatchId,Price,Tribina,Red,Sedishte,Id")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ticketService.UpdateTicket(ticket);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MatchId"] = new SelectList(matchService.GetAllMatches(), "Id", "Location", ticket.MatchId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = ticketService.GetTicket(id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var ticket = ticketService.GetTicket(id);
            if (ticket != null)
            {
                ticketService.DeleteTicket(id);
            }

           return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(Guid id)
        {
            return ticketService.GetTicket(id) != null;
        }

        public IActionResult AddToCart(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = ticketService.GetTicket(id);

            TicketInShoppingCart ts = new TicketInShoppingCart();

            if (ts != null)
            {
                ts.TicketId = match.Id;
                ts.Ticket = match;
                

            }

            return View(ts);
        }

        [HttpPost]
        public IActionResult AddToCartConfirmed(TicketInShoppingCart model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            shoppingCartService.AddToShoppingConfirmed(model, userId);



            return View("Index", ticketService.GetAllTickets());
        }
    }
}

SportsEventApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportsEventApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsEventApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportsEventApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Index">Matches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SportEvents" asp-action="Index">Sport Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCarts" asp-action="Index">ShoppingCarts

                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SportsEventApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>